---
- name: Template dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure dnsmasq listens on the OVS bridge
  lineinfile:
    path: /etc/dnsmasq.conf
    line: "interface={{ ovs_bridge_name }}"
    state: present