---
- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes

- name: Configure iptables for NAT
  shell: |
    iptables -t nat -A POSTROUTING -o {{ nat_external_interface }} -j MASQUERADE
    iptables -A FORWARD -i {{ ovs_bridge_name }} -o {{ nat_external_interface }} -j ACCEPT
    iptables -A FORWARD -i {{ nat_external_interface }} -o {{ ovs_bridge_name }} -m state --state RELATED,ESTABLISHED -j ACCEPT
  args:
    executable: /bin/bash

- name: Save iptables rules
  command: iptables-save > /etc/iptables/iptables.rules